FROM python:3.13.9-alpine

RUN apk add --no-cache gosu git tini docker-cli docker-cli-compose tzdata docker

RUN pip install --no-cache-dir aiodocker setuptools requests jinja2

# renovate: datasource=github-releases depName=actions/runner
ARG RUNNER_VERSION=2.337.0
ENV RUNNER_IMAGE_VERSION=${RUNNER_VERSION}

ENV PYTHONUNBUFFERED=1
COPY entrypoint.sh /entrypoint.sh
RUN mkdir /app
ADD controller.py /app
ADD docker-compose.yaml.j2 /app
WORKDIR /app

RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/sbin/tini", "--", "/entrypoint.sh"]

CMD ["python", "/app/controller.py"]
