name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - 'VERSION'
      - 'entrypoint.sh'
      - 'dockerfile'
      - 'runner.py'
  workflow_dispatch:
    
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Read version from file
      id: get_version
      run: |
        VERSION=$(cat VERSION)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v6
      with:
        images: ghcr.io/l1p0-m/github-runner-docker
        tags: |
          type=raw,value=latest
          type=raw,value=${{ steps.get_version.outputs.version }}
          type=raw,value=${{ steps.get_version.outputs.version }}-${{ github.sha }}

    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
